### ISSUE TITLE
freeze of the MRX520

### ISSUE THREAD

**Issue by luxus** [nugget/python-anthemav#12]
hello, 
i starting to use home-assistant again and wanna integrate my av to create a universal media player card(and use it in homekit)
i run into some trouble when i activate the integration
my receiver will freeze when i turn it off and on again. the LED gets blue and i cannot do anything.. only thing that helps is to unplug the power.
if i disconnect the cable or deactivate the integration the anthem receiver turns off and on fine (the network cable is always connected and i just notices problems since i turned on the home assistant intigration.
any idea what i can do to troubleshoot the problem?

**Comment by nugget** [comment]
What model and firmware version is your AVR?

**Comment by luxus** [comment]
i have now the newest firmware. the freeze on start is gone (sorry that i didnt check the firmware before)
 i created a new isssue for the problem i have now :D
