### ISSUE TITLE
Support for Setting and changing speaker profiles

### ISSUE THREAD

**Issue by blackgold9** [nugget/python-anthemav#32]
Hi! 
Please consider adding support for getting and setting speaker profiles.
I'm interested in automating them via home assistant. 

Thanks!

**Comment by Hyralex** [comment]
What I'm planning to do is to add a service to home assistant that would allow to send any commands to the receiver. To change profile, the command would be SSPxxy (xx=input, y=profile).

**Comment by blackgold9** [comment]
Would the ha component then use that to make a t a top level input/selector?

**Comment by Hyralex** [comment]
It would be more that you could set an input_select in HA and then have an automation to call the service with the selected value.

But this would be a short term solution. I'm planning to add those features directly integrated to the components, but I'll start with listening mode first

**Comment by Hyralex** [comment]
What anthem receiver are you using? how many profile are available?
Edit: Looks like all models x20 and x40 have 4 profiles

**Comment by blackgold9** [comment]
I have the MRX 1140 with 4 speaker profiles.

**Comment by blackgold9** [comment]
I see how the short term approach could be super helpful until you've had time to fully integrate it.

**Comment by blackgold9** [comment]
I just realized this doesn’t work the way I thought it did. Speaker profiles is per-input, so a profile setting would be a bit complicated to use (would involve editing individual inputs).

**Comment by Hyralex** [comment]
I was thinking to implement it based on the current selected input. So when you change the input, it would show the profile for the current input. And changing the profile would save it on the current input. I implemented it for ARC on/off with a switch in home assistant. 
With that done, if your purpose is to apply the same profile to every input, you could then have an automation that set the profile every time the current input is changed.
